- name: Reboot all hosts
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Reboot all hosts
      ansible.builtin.reboot:
        reboot_timeout: 3600
        test_command: uptime
