- name: Restart K3s agents
  hosts: nodes
  gather_facts: false
  become: true
  tasks:
    - name: Check if k3s-agent is installed
      ansible.builtin.command: k3s-agent --version
      register: k3s_agent_version
      changed_when: false
      failed_when: false
      ignore_errors: true

    - name: Restart k3s-agent service
      ansible.builtin.service:
        name: k3s-agent
        state: restarted
      when: k3s_agent_version.rc == 0

- name: Restart K3s master
  hosts: master
  gather_facts: false
  become: true
  tasks:
    - name: Check if k3s is installed
      ansible.builtin.command: k3s --version
      register: k3s_version
      changed_when: false
      failed_when: false
      ignore_errors: true

    - name: Restart k3s service
      ansible.builtin.service:
        name: k3s
        state: restarted
      when: k3s_version.rc == 0
