- name: Retrieve K3s kubeconfig from first master
  hosts: master[0]
  gather_facts: false
  become: true
  tasks:
    - name: Check if k3s is installed
      ansible.builtin.command: k3s --version
      register: k3s_version
      changed_when: false
      failed_when: false
      ignore_errors: true

    - name: Make a duplicate of /etc/rancher/k3s.yaml
      ansible.builtin.copy:
        src: /etc/rancher/k3s/k3s.yaml
        dest: "/tmp/k3s-{{ k3s.cluster_name }}.yaml"
        owner: root
        group: root
        mode: '0600'
        remote_src: true
      when: k3s_version.rc == 0

    - name: Replace server address in kubeconfig
      ansible.builtin.replace:
        path: "/tmp/k3s-{{ k3s.cluster_name }}.yaml"
        regexp: 'server: https://127.0.0.1:6443'
        replace: 'server: https://{{ k3s.master_ip | split("/") | first }}:6443'
      when: k3s_version.rc == 0

    - name: Replace default name with cluster name in kubeconfig
      ansible.builtin.replace:
        path: "/tmp/k3s-{{ k3s.cluster_name }}.yaml"
        regexp: 'default'
        replace: '{{ k3s.cluster_name }}'
      when: k3s_version.rc == 0

    - name: Retrieve kubeconfig from first master node
      ansible.builtin.fetch:
        src: "/tmp/k3s-{{ k3s.cluster_name }}.yaml"
        dest: "/tmp/k3s-{{ k3s.cluster_name }}.yaml"
        flat: true
      when: k3s_version.rc == 0
